name: Common python github action setup

description: >
  Common infrastructure setup which checks out code, sets up python and pipenv,
  and assumes AWS CI role. This requires that the following secrets are set up
  in your Github repository: for an IAM user, the access key id and secret
  access key, as well as a role to assume.

author: Tess Thyer

inputs:

  python_version:
    description: version of python to use
    required: false
    default: "3.10"

  aws_access_key_id:
    description: access key id of the ci user
    required: true

  aws_secret_access_key:
    description: secret access key of the ci user
    required: true

  role_to_assume:
    description: iam role assumed for deployments
    required: true

runs:

  using: composite

  steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install pipenv
        shell: bash
        run: python -m pip install pipenv

      - name: Install dependencies
        env:
          PIPENV_NOSPIN: 'true'
        shell: bash
        run: |
          pipenv install --dev

      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ inputs.aws_access_key_id }}
          aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
          aws-region: us-east-1
          role-to-assume: ${{ inputs.role_to_assume }}
          role-duration-seconds: 1200
